// 50 pre-loaded date missions — marked aiGenerated so they can be filtered out in settings
export const defaultMissions = [

  // ── White (both players can draw) ────────────────────────────────────────────
  { text: 'Cook a dish you\'ve never tried before, together, from scratch.', color: 'white' },
  { text: 'Watch the sunrise together with hot drinks. Say one thing you\'re grateful for.', color: 'white' },
  { text: 'Write each other a letter, seal it, and read it together exactly one year from now.', color: 'white' },
  { text: 'Go on a walk somewhere neither of you has ever been before.', color: 'white' },
  { text: 'Plan your dream vacation together — no budget limits, no filters.', color: 'white' },
  { text: 'Picnic under the stars. Find the darkest spot you can reach.', color: 'white' },
  { text: 'Play a board game. Loser owes the winner one thing of their choice — anything.', color: 'white' },
  { text: 'Dance together in the kitchen to three full songs, no stopping.', color: 'white' },
  { text: 'Visit a gallery or museum. Each pick one piece that moves you most and explain why.', color: 'white' },
  { text: 'Build a playlist of songs that remind you of each other — swap phones and discover.', color: 'white' },
  { text: 'Movie marathon: one film each, no judgment allowed, no phones.', color: 'white' },
  { text: 'Go stargazing and invent names for three constellations you discover together.', color: 'white' },
  { text: 'Day trip somewhere neither of you has been. Pick a direction and go.', color: 'white' },
  { text: 'Cook breakfast in bed for each other, then eat it together without leaving.', color: 'white' },
  { text: 'Build a blanket fort. Spend the whole evening inside it.', color: 'white' },
  { text: 'Write a poem together — one line each, alternating, until it feels done.', color: 'white' },
  { text: 'Take photos around your city like tourists seeing it for the first time.', color: 'white' },
  { text: 'Spend an entire day offline together — no phones, no screens, no exceptions.', color: 'white' },
  { text: 'Visit a local market. Each pick one mystery ingredient for a meal you\'ll cook together.', color: 'white' },
  { text: 'Watch a film from the year the other person was born. Discuss it after.', color: 'white' },

  // ── Blue (drawn by Him) ───────────────────────────────────────────────────────
  { text: 'Plan a surprise date from start to finish — destination, activity, and meal all secret until the day.', color: 'blue' },
  { text: 'Cook her favourite home-made meal. Set the table, light candles, do it properly.', color: 'blue' },
  { text: 'Give her a one-hour massage. No time limits, no interruptions.', color: 'blue' },
  { text: 'Read her favourite book, then sit down and talk about it with her.', color: 'blue' },
  { text: 'Draw her portrait. No matter the skill level — present it seriously and frame it.', color: 'blue' },
  { text: 'Write five things that make her extraordinary. Read them aloud, looking at her.', color: 'blue' },
  { text: 'Plan a midnight walk to somewhere she\'s mentioned wanting to see.', color: 'blue' },
  { text: 'Bring her flowers on a completely random day, for no reason at all.', color: 'blue' },
  { text: 'Take her to a place she loves that you haven\'t been to with her yet.', color: 'blue' },
  { text: 'Spend a whole evening doing only her favourite things — she chooses everything.', color: 'blue' },
  { text: 'Make a photobook of your best memories together and give it to her.', color: 'blue' },
  { text: 'Learn one song that means something to her and perform it, however imperfectly.', color: 'blue' },
  { text: 'Plan a film evening around only her favourite genre — no compromises.', color: 'blue' },
  { text: 'Write her a letter about your single favourite memory you share. Give it to her.', color: 'blue' },
  { text: 'Plan a spontaneous trip: she only finds out the destination on the day you leave.', color: 'blue' },

  // ── Pink (drawn by Her) ───────────────────────────────────────────────────────
  { text: 'Plan a surprise date from start to finish — destination, activity, and meal all secret until the day.', color: 'pink' },
  { text: 'Bake his favourite treat from scratch. No shortcuts, no mixes.', color: 'pink' },
  { text: 'Give him a full evening of his favourite game or show — zero interruptions, zero complaints.', color: 'pink' },
  { text: 'Recreate your first date together as closely as you can remember it.', color: 'pink' },
  { text: 'Write five things that make him extraordinary. Read them aloud, looking at him.', color: 'pink' },
  { text: 'Plan a cozy night in built entirely around his favourite comforts — his choice of everything.', color: 'pink' },
  { text: 'Watch a film he loves that you\'ve never given a real chance — pay full attention.', color: 'pink' },
  { text: 'Draw his portrait. No matter the skill level — present it seriously and frame it.', color: 'pink' },
  { text: 'Plan an outing to a place he\'s mentioned wanting to visit. Make it happen.', color: 'pink' },
  { text: 'Spend a whole evening doing only his favourite things — he chooses everything.', color: 'pink' },
  { text: 'Send him a genuine good morning message every day for one week.', color: 'pink' },
  { text: 'Learn the lyrics to one of his favourite songs and perform it for him.', color: 'pink' },
  { text: 'Write him a letter about your single favourite memory you share. Give it to him.', color: 'pink' },
  { text: 'Prepare a midnight snack spread of every favourite thing he loves.', color: 'pink' },
  { text: 'Build an evening around all his favourites — the film, the food, the atmosphere, all his.', color: 'pink' },
];
